urls.py
from django.urls import path, include

from customer_service.views import manage, profile

app_name = 'customer_service'

urlpatterns = [
    path('manage/', include([
        path('<int:pk>/edit/', manage.CSEditAccount.as_view(), name='manage_edit_account'),
        path('add/', manage.CreateCSAccount.as_view(), name='manage_create_account'),
        path('inactive/', manage.InactiveListCSAccountsView.as_view(), name='manage_inactive_list'),
        path('', manage.ListCSAccountsView.as_view(), name='manage_list')
    ])),
    path('<int:pk>/', include([
        path('password/', profile.ChangePasswordView.as_view(), name='edit_password'),
        path('departments/', profile.ChangeDepartmentView.as_view(), name='edit_department'),
        path('edit-profile/', profile.CSEditProfile.as_view(), name='edit_profile'),
        path('', profile.ProfileOverView.as_view(), name='profile_overview'),
    ])),
]

forms/profile.py
from django import forms

from customer_service.models import Profile
from utility.forms import AvatarWidget
from center.models import Branch, Department


class EditProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=AvatarWidget)

    class Meta:
        model = Profile
        exclude = 'active', 'deleted', 'user', 'branch', 'department',
    
    def save(self):        
        email = self.cleaned_data.pop('email')
        instance = super().save()
        instance.user.email = email
        instance.user.save()
        return instance


class EditDepartmentForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = 'department',

    def __init__(self, *args, **kwargs):
        center = kwargs.pop("center")     # client is the parameter passed from views.py
        super().__init__(*args, **kwargs)
        self.fields['department'] = forms.ModelMultipleChoiceField(
            queryset=Department.objects.filter(branches__center=center, parent__isnull=True).distinct(),
            required=True,
            widget=forms.CheckboxSelectMultiple()
        )

    def save(self):
        department = self.cleaned_data.pop('department')
        profile = self.instance
        profile.department.set(department, clear=True)
        return profile

views/profile.py
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render

from customer_service.models import Profile, CustomerServes
from customer_service.forms import profile


class ProfileOverView(DetailView):
    model = Profile
    template_name = 'customer_service/overview.html'


class CSEditProfile(UpdateView):
    model = Profile
    form_class = profile.EditProfileForm
    template_name = 'customer_service/edit_profile.html'

    def get_success_url(self):
        return reverse_lazy('customer_service:profile_overview', kwargs={'pk': self.object.pk})


class ChangePasswordView(PasswordChangeView):
    model = CustomerServes
    template_name = 'customer_service/change_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(pk=self.kwargs.get('pk'))
        return context

    def get_success_url(self):
        return reverse_lazy('customer_service:profile_overview', kwargs={'pk': self.object.pk})


class ChangeDepartmentView(UpdateView):
    model = Profile
    form_class = profile.EditDepartmentForm
    template_name = 'customer_service/change_department.html'

    def dispatch(self, request, *args, **kwargs):
        center = self.request.session.get('center', None)
        if request.user.role != 3 and center:
            return super(ChangeDepartmentView, self).dispatch(request, *args, **kwargs)
        return render(request, '404.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(pk=self.kwargs.get('pk'))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'center': self.request.session.get('center')})
        return kwargs

    def get_success_url(self):
        messages.success(self.request, 'Customer Service details updated!')
        return reverse_lazy('customer_service:profile_overview', kwargs={'pk': self.object.pk})

templates/customer_service/profile/layout.html
{% extends 'layout/admin.html' %}
{% load static %}


{% block left_subheader %}
<button class="kt-subheader__mobile-toggle kt-subheader__mobile-toggle--left"
    id="kt_subheader_mobile_toggle"><span></span></button>
<h3 class="kt-subheader__title">
    {% if request.session.profile.pk == profile.pk %}
    My Profile
    {% else %}
    {{profile.full_name}}
    {% endif %}
</h3>
<span class="kt-subheader__separator kt-hidden"></span>
<div class="kt-subheader__breadcrumbs">
    <a href="#" class="kt-subheader__breadcrumbs-home">
        <i class="flaticon2-shelter"></i>
    </a>
    <span class="kt-subheader__breadcrumbs-separator"></span>
    <a href="{% url 'customer_service:manage_list' %}" class="kt-subheader__breadcrumbs-link">Customer Service</a>
</div>
{% endblock left_subheader %}

{% block content %}
<div class="kt-content kt-grid__item kt-grid__item--fluid" id="kt_content">
    <!--Begin::App-->
    <div class="kt-grid kt-grid--desktop kt-grid--ver kt-grid--ver-desktop kt-app">
        <!--Begin:: App Aside Mobile Toggle-->
        <button class="kt-app__aside-close" id="kt_user_profile_aside_close">
            <i class="la la-close"></i>
        </button>
        <!--End:: App Aside Mobile Toggle-->

        <!--Begin:: App Aside-->
        {% include 'customer_service/profile/aside.html' %}
        <!--End:: App Aside-->

        <!--Begin:: App Content-->
        <div class="kt-grid__item kt-grid__item--fluid kt-app__content">{% block profile_content %}{% endblock %}</div>
        <!--End:: App Content-->
    </div>
    <!--End::App-->
</div>
{% endblock content %}


{% block scripts %}
<script src="{% static 'vendors/metronic/pages/profile.js' %}"></script>
{% endblock scripts %}